/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rc522_spi_api_RC522 */

#ifndef _Included_rc522_spi_api_RC522
#define _Included_rc522_spi_api_RC522
#ifdef __cplusplus
extern "C" {
#endif
#undef rc522_spi_api_RC522_MODE
#define rc522_spi_api_RC522_MODE 0L
#undef rc522_spi_api_RC522_BITS
#define rc522_spi_api_RC522_BITS 8L
#undef rc522_spi_api_RC522_SPEED
#define rc522_spi_api_RC522_SPEED 10000L
#undef rc522_spi_api_RC522_PICC_REQALL
#define rc522_spi_api_RC522_PICC_REQALL 82L
#undef rc522_spi_api_RC522_PICC_AUTHENT1A
#define rc522_spi_api_RC522_PICC_AUTHENT1A 96L
/*
 * Class:     rc522_spi_api_RC522
 * Method:    open
 * Signature: (Ljava/lang/String;BBI)I
 */
JNIEXPORT jint JNICALL Java_rc522_1spi_1api_RC522_open
  (JNIEnv *, jclass, jstring, jbyte, jbyte, jint);

/*
 * Class:     rc522_spi_api_RC522
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_rc522_1spi_1api_RC522_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     rc522_spi_api_RC522
 * Method:    request
 * Signature: (B[B)I
 */
JNIEXPORT jint JNICALL Java_rc522_1spi_1api_RC522_request
  (JNIEnv *, jclass, jbyte, jbyteArray);

/*
 * Class:     rc522_spi_api_RC522
 * Method:    anticoll
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_rc522_1spi_1api_RC522_anticoll
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     rc522_spi_api_RC522
 * Method:    select
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_rc522_1spi_1api_RC522_select
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     rc522_spi_api_RC522
 * Method:    auth_state
 * Signature: (BB[B[B)I
 */
JNIEXPORT jint JNICALL Java_rc522_1spi_1api_RC522_auth_1state
  (JNIEnv *, jclass, jbyte, jbyte, jbyteArray, jbyteArray);

/*
 * Class:     rc522_spi_api_RC522
 * Method:    read
 * Signature: (B[B)I
 */
JNIEXPORT jint JNICALL Java_rc522_1spi_1api_RC522_read
  (JNIEnv *, jclass, jbyte, jbyteArray);

/*
 * Class:     rc522_spi_api_RC522
 * Method:    write
 * Signature: (B[B)I
 */
JNIEXPORT jint JNICALL Java_rc522_1spi_1api_RC522_write
  (JNIEnv *, jclass, jbyte, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
